#!/bin/bash
if  dpkg-query -W -f='${Status}' php7.0 libapache2-mod-php7.0 php7.0-mysql php-common php7.0-cli php7.0-common php7.0-json php7.0-opcache php7.0-readline | grep -c "ok installed"
then
	echo "PHP koos vajalike pakettidega on juba paigaldatud"
	else
apt-get --assume-yes install php7.0 libapache2-mod-php7.0 php7.0-mysql php-common php7.0-cli php7.0-common php7.0-json php7.0-opcache php7.0-readline
fi
