#!/bin/bash
if  dpkg-query -W -f='${Status}' apache2 mysql-server php7.0 libapache2-mod-php7.0 php7.0-mysql php-common php7.0-cli php7.0-common php7.0-json php7.0-opcache php7.0-readline | grep -c "ok installed"
then
echo "Andmebaasi nimi: "
read dbname
echo "Andmebaasi kasutaja: "
read dbuser
echo "Andmebaasi parool: "
read dbpass
echo "CREATE USER 'wpuser'@'localhost' IDENTIFIED BY 'qwerty';" | mysql -u root -pqwerty
echo "CREATE DATABASE wp_database;" | mysql -u root -pqwerty
echo "GRANT ALL ON wp_database.* TO wpuser@localhost;" | mysql -u root -pqwerty
echo "FLUSH PRIVILEGES;" | mysql -u root -pqwerty
curl -O https://wordpress.org/latest.tar.gz
tar -zxvf latest.tar.gz
cd wordpress
cp -rf . /var/www/html/wordpress
cd /var/www/html/wordpress
cp wp-config-sample.php wp-config.php
perl -pi -e "s/database_name_here/$dbname/g" wp-config.php
perl -pi -e "s/username_here/$dbuser/g" wp-config.php
perl -pi -e "s/password_here/$dbpass/g" wp-config.php

perl -i -pe'
  BEGIN {
    @chars = ("a" .. "z", "A" .. "Z", 0 .. 9);
    push @chars, split //, "!@#$%^&*()-_ []{}<>~\`+=,.;:/?|";
    sub salt { join "", map $chars[ rand @chars ], 1 .. 64 }
  }
  s/put your unique phrase here/salt()/ge
' wp-config.php

mkdir wp-content/uploads
chmod 775 wp-content/uploads
echo "Paigaldus on valmis!"
else
	echo "Paigalda enne vajalikud paketid!"
fi
