#!/bin/bash
kasutajanimi=$1
owner=$(ls -ld /home/$kasutajanimi/public/ | awk '{print $3}')
if [ -d /home/$kasutajanimi/public ]; then
  echo "Antud kaust on juba varasemalt loodud"
  if [ "$owner" = "$kasutajanimi" ]; then
	echo "Antud kaustale on juba korrektsed õigused antud."
  else
  	chown -R $kasutajanimi /home/$kasutajanimi/public 
  fi
else
	useradd -m -s /bin/bash $kasutajanimi
  	mkdir /home/$kasutajanimi/public
  	if [ "$owner" = "$kasutajanimi" ]; then
		echo "Õigused on juba korrektsed."
  	else
  	chown -R $kasutajanimi /home/$kasutajanimi/public
  fi
fi
