#!/bin/bash
sed -i 's/public_html/public/g' /etc/apache2/mods-available/userdir.conf
a2enmod userdir
service apache2 restart

kasutajanimi=$1
useradd -m -s /bin/bash $kasutajanimi
mkdir /home/$kasutajanimi/public
