#!/bin/bash
#
#Kasutaja loomine
while read line
do
	kasutaja=$line
	parool=$(pwgen -s 8 1)
	echo "$kasutaja parooliks määratakse $parool"
	useradd -m -s /bin/bash $kasutaja
	echo "$kasutaja:$parool" | chpasswd
	echo "$kasutaja:$parool" >>  "genkasutajaparool"
done < $1
